trigger:
  branches:
      include:
        - main
        - azure-pipelines
  paths:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '16'
- script: |
    npm install
    yarn build
    npx keycloakify
- task: CopyFiles@2
  inputs:
    Contents: 'build_keycloak/target/cv-manager-keycloak-theme-4.8.2.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'