trigger:
  branches:
      include:
        - main
  paths:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- task: NodeTool@0
  inputs:
    versionSpec: '18'
- script: |
    npm install
    npm run build-keycloak-theme
    cp build_keycloak/target/keycloak-theme-for-kc-all-other-versions.jar build_keycloak/target/cv-manager-keycloak-theme-4.8.2.jar
- task: CopyFiles@2
  inputs:
    Contents: 'build_keycloak/target/cv-manager-keycloak-theme-4.8.2.jar'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
# Publish the artifacts directory for consumption in publish pipeline
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'jpo-cvmanager-keycloakify'
    publishLocation: 'Container'
